### PR TITLE
Create CircleCI config

### LINKED ISSUE #53: Change CI to CircleCI
**Is your feature request related to a problem or issue? Please describe or annex.**
Travis CI is too buggy

**Purpose the solution you'd like**
Change to CircleCI

**Describe alternatives you've considered**

**Additional context**
Our PRs always fail due to test problems in Travis CI

### PR DESCRIPTION
**Pull request by PurpleMyst**
Hi! So this CircleCI config *should be* working, but for whatever reason the `entity_history` test fails on the latest commit. Was this already the case or is there a bug in my config? If the latter, let me know and I will fix it. :>

Resolves #53

### CODE REVIEW

**Comment by otaviopace** [comment]
Hey @PurpleMyst, thanks for the Pull Request!!! :blush: 

I didn't know that CircleCI had parameters like that, cool!

Also, do you know how to make beta/stable toolchains be able to fail? We had that configured on `travis`.

**Comment by naomijub** [comment]
Hi @PurpleMyst 
`entity_history` doesn't seem to fail at master:
```
2.60s$ cargo run --example entity_history
   Compiling transistor v1.3.11 (/home/travis/build/naomijub/transistor)
    Finished dev [unoptimized + debuginfo] target(s) in 2.54s
     Running `target/debug/examples/entity_history`
EntityHistoryResponse { history: [EntityHistoryElement { db___valid_time: 2020-09-27T02:28:27.754+00:00, tx___tx_id: 5, tx___tx_time: 2020-09-27T02:28:27.754+00:00, db___content_hash: "2da097a2dffbb9828cd4377f1461a59e8454674b", db__doc: Some(Map(Map({":crux.db/id": Key(":hello-history"), ":first-name": Str("Hello"), ":last-name": Str("World")}))) }] }
EntityHistoryResponse { history: [EntityHistoryElement { db___valid_time: 2020-09-27T02:28:27.754+00:00, tx___tx_id: 5, tx___tx_time: 2020-09-27T02:28:27.754+00:00, db___content_hash: "2da097a2dffbb9828cd4377f1461a59e8454674b", db__doc: None }] }
The command "cargo run --example entity_history" exited with 0.
```

**Comment by naomijub** [comment]
Also your branch is passing https://app.circleci.com/pipelines/github/PurpleMyst/transistor/13/workflows/312a1302-4ae1-49dc-81c0-3b713b8509ac/jobs/31/parallel-runs/0/steps/0-109

**Comment by PurpleMyst** [comment]
> 
> 
> Hey @PurpleMyst, thanks for the Pull Request!!! 😊
> 
> I didn't know that CircleCI had parameters like that, cool!
> 
> Also, do you know how to make beta/stable toolchains be able to fail? We had that configured on `travis`.

Sadly, I do not believe that is a feature CircleCi supports out of the box. And, looking into it slightly, the only Ci environments that seem to support this feature are Travis CI and Gitlab Ci. That's a shame, because it's a genuinely useful feature.

I can either try a work-around, write a Gitlab CI configuration instead of CircleCI, or leave everything as-is. Which one do you want me to do?

**Comment by otaviopace** [comment]
So, I've talked with @naomijub and we think we probably it isn't a issue to require all toolchains to pass, if it starts too fail too often, we can remove them or do the work around, I'll merge it for now :slightly_smiling_face:

**Comment by otaviopace** [comment]
Aaaaand it passed :tada: 
https://app.circleci.com/pipelines/github/naomijub/transistor/3/workflows/27963a87-87b4-42bb-861e-d96a9c494d5e

I mean, I had to run it more than once, but it was because of the Crux database, it sometimes fails to respond a request, we had the same issue on TravisCI.

**Pull request merged**
